CREATE TABLE LOCATIONS_TEST (
    COMPANY1_ID NUMBER
    ,COMPANY2_ID NUMBER
    ,COMPANY3_ID NUMBER
    ,COMPANY4_ID VARCHAR2(30)
    ,COMPANY5_ID NUMBER
    ,NAME VARCHAR2(50)
    ,ADDRESS VARCHAR2(100)
    ,LOCATION VARCHAR2(100)
    ,CITY VARCHAR2(100)
    ,STATE VARCHAR2(2)
    ,ZIPCODE VARCHAR2(15)
    ,LATITUDE NUMBER(17, 14)
    ,LONGITUDE NUMBER(17, 14)
    ,FUEL_PRICE NUMBER(6, 3)
    ,FUEL_PRICE_DATE TIMESTAMP
    ,LOCATION_TYPE VARCHAR2(5)
);